name = "ExtendedKronigPennyMatrix"
uuid = "0edef5b7-0e89-49b4-9493-3bcd9a743ed9"
authors = ["Hiroharu Sugawara <hsugawa@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
